// LeLinkHLSServer.idl : IDL source for LeLinkHLSServer
//

// This file will be processed by the MIDL tool to
// produce the type library (LeLinkHLSServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E818F2A8-B32A-44C6-A90C-F873CA99742C),
	version(1.0),
]
library LeLinkHLSServerLib
{
	importlib("stdole2.tlb");
};

